### ISSUE TITLE
Font caching? 

### ISSUE THREAD

**Issue by aaronbell** [typemytype/drawbot#56] opened 2016-07-20 18:33 UTC
I wrote to Erik about this yesterday, but figured I'd post it here too. I'm running into what appears to be a font caching problem.

Script in question (adapted from Erik's sample script):
`
path = PATH_TO_OTF
fontName = installFont(path)
size(1000, 1000)

thisFontSize = 242
s = FormattedString(
    txt="fe AV,",
    font="",
    fontSize=312,
)
textBox(s , (50, 50, width()-50, height()-1.5*50))
uninstallFont(path)
`

To repro:
1) Open any font editor and generate an OTF.
2) Replace the PATH_TO_OTF above with the path to the OTF. 
3) Run the script. 
4) Edit the font, increasing kerning between A and V by 200 and regenerate the OTF. 
5) Run the script. 
6) _Note that nothing has changed in the viewport_
7) Close Drawbot. 
8) Reopen Drawbot. 
9) Run script. 
10) _Note that the kern change performed in step 4 is now visible_

Similarly, instead of closing and reopening drawbot, change the font being used from the non-installed font to something like Helvetica. Run the script once, then change it back. The changes will be visible. 

My guess is that there is some font caching going on and Drawbot does not re-load the font each time the script is run. It could also be that I'm not uninstalling the font properly.

**Comment by justvanrossum** [comment] 2017-12-15 10:31
Duplicate of #112. Or rather vice versa, but there's more discussion there, so let's continue there.

**Closed by justvanrossum** 2017-12-15 10:31 UTC
