### ISSUE TITLE
Setting tracking in a FormattedString causes DrawBot to crash

### ISSUE THREAD

**Issue by CalderH** [typemytype/drawbot#458] opened 2021-12-07 07:25 UTC
I have a program that adds data to a FormattedString, alternating between a header style (for people’s names) and a smaller style (for information about them). I add the small-text information by creating a separate FormattedString with that text, using that string’s .size() information to add line breaks in the right places, and then appending that FormattedString to the main FormattedString.

A specific person has some info that is slightly too wide for the text box, so (as a temporary solution) I added a case to test for whether it was them, and if so, decrease the tracking of their information before appending their FormattedString to the main one. However, adding the tracking-change line causes DrawBot to crash when the program runs. I haven’t found a way to reproduce the error in a simpler program (simply creating a FormattedString, appending some text to it, creating a second FormattedString with different tracking, appending some text to that, and then appending the second FormattedString to the first works fine).

If you’d like I can attach the file; I’ll just have to spend a moment editing out some inessential/possibly confidential info.

**Comment by justvanrossum** [comment] 2021-12-07 07:26
A small reproducer would be great!

**Comment by CalderH** [comment] 2021-12-07 08:09
Okay, I did manage to come up with a much smaller program that causes a similar error:
```
txt = FormattedString()
fake_database = [('', ''), ('One Two Three', 'Four Five Six')]
for data_row in fake_database:
    name, info = data_row
    txt += name + '\n'
    info_txt = FormattedString()
    if info == '':
        info_txt.tracking(-1)
        info_txt += 'Hello'
    else:
        info_txt += 'Hello'
    txt += info_txt
textBox(txt, (0, 0, 200, 200))
```
Removing the tracking line makes it no longer crash. Also, editing the string 'One Two Three' to 'One Two' makes it no longer crash, for some reason.

**Comment by typemytype** [comment] 2021-12-07 08:36
oh nice one, to simplify the example: adding tracking to an `\n` seems to fail somehow

```python
t = FormattedString()
t.fontSize(100)
t.tracking(-10)
t += "\n"
t.tracking(0)
t += "hello"

textBox(t, (30, 30, 300, 600))
```

**Comment by CalderH** [comment] 2021-12-08 02:39
Is adding tracking to `\n` necessarily the issue? I tried to separate the tracking adjustment from the `\n` by doing the following (in the original program), but it still crashed.

```
conc_txt.tracking(-1)
conc_txt += 'Social Innovation and Entrepreneurship |'
conc_txt.tracking(0)
conc_txt += '\n'
```

**Comment by typemytype** [comment] 2021-12-08 08:13
yep an other case:

```python
t = FormattedString()
t.tracking(-10)
t += "foo"
t.tracking(0)
t += "\nbar"

newPage(200, 200)
textBox(t, (10, 10, 180, 180))
```

it happens when the a new line starts outside the box...

**Comment by typemytype** [comment] 2021-12-08 08:25
strangely it works fine when some tracking is set...

```python
# this works
t = FormattedString()
t.tracking(-10)
t += "foo"
t.tracking(-10)
t += "\nbar"

print(t.size())

newPage(200, 200)
textBox(t, (10, 10, 180, 180))


t = FormattedString()
t.tracking(-10)
t += "foo"
t.tracking(10)
t += "\nbar"

print(t.size())

newPage(200, 200)
textBox(t, (10, 10, 180, 180))
```

**Comment by typemytype** [comment] 2021-12-27 15:25
This CoreText bug seems to be resolved in Monterey.

**Comment by typemytype** [comment] 2022-01-24 10:11
to confirm this is fixed on Monterey

**Closed by typemytype** 2022-01-24 10:11 UTC
