### ISSUE TITLE
FormattedString font path error in 3.127+

### ISSUE THREAD

**Issue by rutherfordcraze** [typemytype/drawbot#438] opened 2021-09-25 11:11 UTC
After upgrading to 3.128 (from 3.126) I’ve started seeing this error when referencing certain fonts by filename in a FormattedString, but not when using the `font()` method directly: `*** DrawBot warning: not font could be found for <font> ***`.

I’ve checked with 3.127 and the issue is present there as well.
From what I can it’s specific to certain fonts.
It doesn’t make a difference if the path is relative, absolute, or only the filename.

<img width="1340" alt="Screenshot 2021-09-25 at 12 53 25" src="https://user-images.githubusercontent.com/17358105/134768995-b9896f2a-d3bb-4e1f-a7c0-3ba2deaf194b.png">

```
font_path = "./MDGreymarch-Gem.otf"

newPage(100, 100)

text_fs = FormattedString()
text_fs.append("hallo\nI'm Times", font = font(font_path))
textBox(text_fs, (10, 50, 50, 25))

font(font_path)
textBox("hallo\nI'm Times", (10, 10, 50, 25))
```

**Comment by justvanrossum** [comment] 2021-09-25 11:27
Try replacing `font = font(font_path)` with font=font_path`. 

The return value of `font()` is the font name, but the font isn't installed, so it can't be found by name. In previous DrawBots, using the path would temporarily install the font, so referencing it by name after you did `font(font_path)` would have worked. This is no longer the case: a font referenced by path/filename is no longer "installed", but used directly.

This is more or less a duplicate of #429.

**Comment by rutherfordcraze** [comment] 2021-09-25 11:46
Thanks Just, that makes sense (and your suggestion works).

**Closed** 2021-09-25 11:51 UTC
